# Generated by Django 6.0.3 on 2026-03-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_progress',
            field=models.IntegerField(default=0),
        ),
    ]
