# Generated by Django 6.0.3 on 2026-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_employee_onboarding_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
