# Generated by Django 6.0.3 on 2026-03-24 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_delete_user'),
        ('onboarding', '0010_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.employee'),
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='assigned_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
