# Generated by Django 6.0.3 on 2026-03-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_remove_employee_user_alter_document_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
